version: '3.5'

services:
  cadvisor:
    image: google/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
    networks:
      - shared
      - traefik_traefik-public
    deploy:
      mode: global
    labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik_traefik-public"
        - "traefik.http.routers.cadvisor.entrypoints=websecure"
        - "traefik.http.routers.cadvisor.rule=Host(`cadvisor.${DOMAIN:-localhost}`)"
        - "traefik.http.routers.cadvisor.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.cadvisor.loadbalancer.server.port=8080"

  node-exporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - ./configs/hostname:/etc/host_hostname
    ports:
      - 9100:9100
    environment:
      - HOST_HOSTNAME=/etc/host_hostname
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points'
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
      - '--collector.textfile.directory=/etc/node-exporter/'
    networks:
      - shared
    deploy:
      mode: global

  blackbox-exporter:
    image: prom/blackbox-exporter:v0.12.0
    networks:
      - shared

  alertmanager:
    image: prom/alertmanager
    configs:
      - source: alertmanager_config
        target: /etc/alertmanager/config.yml
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    volumes:
      - alertmanager:/alertmanager
    networks:
      - shared
      - traefik_traefik-public
    deploy:
      replicas: 1
      placement:
        constraints:
           - node.role==manager
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik_traefik-public"
        - "traefik.http.routers.alertmanager.entrypoints=websecure"
        - "traefik.http.routers.alertmanager.rule=Host(`alertmanager.${DOMAIN:-localhost}`)"
        - "traefik.http.routers.alertmanager.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.alertmanager.loadbalancer.server.port=9093"

  prometheus:
    image: prom/prometheus
    user: root
    volumes:
      - promconfig:/etc/prometheus
      - promdata:/prometheus
    configs:
      - source: prometheus_config2
        target: /etc/prometheus/prometheus.yml
      - source: prometheus_rules
        target: /etc/prometheus/alert.rules
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
    networks:
      - shared
      - traefik_traefik-public
    deploy:
      placement:
        constraints:
          - node.role==manager
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik_traefik-public"
        - "traefik.http.routers.prometheus.entrypoints=websecure"
        - "traefik.http.routers.prometheus.rule=Host(`prometheus.${DOMAIN:-localhost}`)"
        - "traefik.http.routers.prometheus.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.prometheus.loadbalancer.server.port=9090"

  grafana:
    image: grafana/grafana
    volumes:
      - grafanadata:/var/lib/grafana
      - grafana_provisioning:/etc/grafana/provisioning
    configs:
      - source: grafana_config_datasource
        target: /etc/grafana/provisioning/datasources/prometheus.yml
      - source: grafana_config_dashboard
        target: /etc/grafana/provisioning/dashboards/ds_prometheus.yml
      - source: grafana_config_mydash
        target: /etc/grafana/provisioning/dashboards/DockerMonitoring.json
      - source: grafana_config_mydash2
        target: /etc/grafana/provisioning/dashboards/DockerPrometheusMonitoring.json
      - source: grafana_config_bbe
        target: /etc/grafana/provisioning/dashboards/BlackboxExporter.json
      - source: grafana_config_mysql
        target: /etc/grafana/provisioning/dashboards/MysqlOverview.json
    environment:
      - GF_SERVER_ROOT_URL=http://grafana.${DOMAIN:-localhost}
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
      - PROMETHEUS_ENDPOINT=http://prometheus:9090
    networks:
      - traefik_traefik-public
      - shared
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==manager
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik_traefik-public"
        - "traefik.http.routers.grafana.entrypoints=websecure"
        - "traefik.http.routers.grafana.rule=Host(`grafana.${DOMAIN:-localhost}`)"
        - "traefik.http.routers.grafana.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.grafana.loadbalancer.server.port=3000"

networks:
  shared:
    name: shared
    driver: overlay
  traefik_traefik-public:
    name: traefik_traefik-public
    driver: overlay
    external: true

volumes:
  promconfig: {}
  promdata: {}
  grafanadata: {}
  alertmanager: {}
  grafana_provisioning: {}

configs:
  alertmanager_config:
    file: ./alertmanager/configs/alertmanager.yml
  prometheus_config2:
    file: ./prometheus/configs/prometheus.yml
  prometheus_rules:
    file: ./prometheus/rules/alert.rules
  grafana_config_datasource:
    file: ./grafana/provisioning/datasources/prometheus.yml
  grafana_config_dashboard:
    file: ./grafana/provisioning/dashboards/ds_prometheus.yml
  grafana_config_mydash:
    file: ./grafana/provisioning/dashboards/DockerMonitoring.json
  grafana_config_mydash2:
    file: ./grafana/provisioning/dashboards/DockerPrometheusMonitoring.json
  grafana_config_bbe:
    file: ./grafana/provisioning/dashboards/BlackboxExporter.json
  grafana_config_mysql:
    file: ./grafana/provisioning/dashboards/MysqlOverview.json
